begin
    for identity_column in (
        select table_name, column_name
          from user_tab_identity_cols
         order by table_name, column_name
    ) loop
        execute immediate
            'alter table "' || identity_column.table_name || '" modify ("' ||
            identity_column.column_name ||
            '" generated by default on null as identity (start with limit value))';
    end loop;
    dbms_utility.compile_schema(schema => user, compile_all => false);
end;
/
