insert all
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, created_at, last_updated_at)
    values (101, 'REQ-2026-0101', 'Draft', 'Draft Demo Services', 'CORPORATE', 'PK', 1, 'requester_a', 'Draft retained for incremental completion.', 'Facilities', 150000, 'PK-NTN-DRAFT01', systimestamp - interval '7' day, systimestamp - interval '1' day)
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, created_at, submitted_at, last_updated_at)
    values (102, 'REQ-2026-0142', 'Correction Requested', 'BluePeak Facilities', 'CORPORATE', 'PK', 1, 'requester_a', 'Regional facilities maintenance and emergency support.', 'Facilities', 480000, null, systimestamp - interval '6' day, systimestamp - interval '5' day, systimestamp - interval '2' day)
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, created_at, submitted_at, last_updated_at)
    values (103, 'REQ-2026-0138', 'Under Review', 'Nexa Office Supply', 'CORPORATE', 'PK', 1, 'requester_a', 'Office supplies for three operating sites under the approved sourcing plan.', 'Office Supplies', 275000, 'PK-NTN-NEXA38', systimestamp - interval '8' day, systimestamp - interval '4' day, systimestamp - interval '4' day)
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, created_at, submitted_at, last_updated_at)
    values (104, 'REQ-2026-0122', 'Marked Duplicate', 'Al Noor Packaging', 'CORPORATE', 'PK', 1, 'requester_b', 'Packaging supply requirement.', 'Packaging', 620000, 'PK-NTN-100884', systimestamp - interval '12' day, systimestamp - interval '10' day, systimestamp - interval '8' day)
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, created_at, submitted_at, last_updated_at)
    values (105, 'REQ-2026-0150', 'Approved', 'Atlas Safety Equipment', 'CORPORATE', 'AE', 2, 'requester_b', 'Approved industrial safety equipment sourcing.', 'Safety Equipment', 910000, 'AE-TRN-ATLAS50', systimestamp - interval '9' day, systimestamp - interval '7' day, systimestamp - interval '2' day)
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, fusion_supplier_id, fusion_supplier_number, fusion_created_at, fusion_response_ref, created_at, submitted_at, last_updated_at)
    values (106, 'REQ-2026-0129', 'Created in Fusion', 'Orion Technical Textiles', 'CORPORATE', 'AE', 2, 'requester_a', 'Technical textile supply for approved production demand.', 'Textiles', 1250000, 'AE-TRN-ORION29', 'FUS-NEW-106', 'SUP-NEW-106', systimestamp - interval '1' day, 'mock://fusion/responses/REQ-2026-0129', systimestamp - interval '14' day, systimestamp - interval '12' day, systimestamp - interval '1' day)
  into supplier_request (request_id, request_number, status, supplier_name, supplier_type_code, country_code, business_unit_id, requester_user, business_justification, product_service_category, expected_annual_spend, tax_registration_number, created_at, submitted_at, last_updated_at)
    values (107, 'REQ-2026-0161', 'Integration Failed', 'Summit Lab Services', 'CORPORATE', 'PK', 3, 'requester_b', 'Accredited laboratory testing for product compliance.', 'Laboratory Services', 340000, 'PK-NTN-SUMMIT61', systimestamp - interval '11' day, systimestamp - interval '9' day, systimestamp - interval '1' hour)
select 1 from dual
where not exists (select 1 from supplier_request where request_id = 101);

insert all
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1001, 101, 'Draft Primary', 'PK', '8 Service Road', 'Office 2', 'Lahore', 'Punjab', '54000', 1, 1)
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1002, 102, 'BluePeak Primary', 'PK', '22 Canal View', 'Suite 4', 'Lahore', 'Punjab', '54000', 1, 1)
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1003, 103, 'Nexa Primary', 'PK', '14 Trade Centre', 'Floor 3', 'Karachi', 'Sindh', '75500', 1, 1)
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1004, 104, 'Noor Primary', 'PK', '12 Industrial Area', null, 'Karachi', 'Sindh', '74000', 1, 1)
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1005, 105, 'Atlas Primary', 'AE', '7 Safety Avenue', 'Warehouse B', 'Dubai', 'Dubai', '00000', 2, 1)
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1006, 106, 'Orion Primary', 'AE', '16 Textile Park', 'Unit 9', 'Dubai', 'Dubai', '00000', 2, 1)
  into supplier_request_site (site_id, request_id, site_name, country_code, address_line1, address_line2, city, region, postal_code, intended_business_unit_id, is_primary) values (1007, 107, 'Summit Primary', 'PK', '5 Science Block', 'Lab 6', 'Islamabad', 'ICT', '44000', 3, 1)
select 1 from dual where not exists (select 1 from supplier_request_site where site_id = 1001);

insert all
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2001, 101, 'Draft Contact', 'draft@demo.example', '+923001110101', 'demo.example')
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2002, 102, 'Sara Ahmed', 'sara@bluepeak.example', '+923001110142', 'bluepeak.example')
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2003, 103, 'Nadia Khan', 'nadia@nexa.example', '+923001110138', 'nexa.example')
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2004, 104, 'Ali Noor', 'ali@alnoor.example', '+9221000100884', 'alnoor.example')
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2005, 105, 'Amal Saeed', 'amal@atlas.example', '+971500001050', 'atlas.example')
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2006, 106, 'Omar Tariq', 'omar@oriontextile.example', '+971500001060', 'oriontextile.example')
  into supplier_request_contact (contact_id, request_id, contact_name, contact_email, phone_number, email_domain) values (2007, 107, 'Hina Aslam', 'hina@summitlab.example', '+923001110161', 'summitlab.example')
select 1 from dual where not exists (select 1 from supplier_request_contact where contact_id = 2001);

insert all
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3001, 101, 'PK', '****0101', '0101', 'sha256:demo-bank-token-0101', 1)
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3002, 102, 'PK', '****0142', '0142', 'sha256:demo-bank-token-0142', 1)
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3003, 103, 'PK', '****0138', '0138', 'sha256:demo-bank-token-0138', 1)
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3004, 104, 'PK', '****0884', '0884', 'sha256:demo-bank-token-100884', 1)
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3005, 105, 'AE', '****0150', '0150', 'sha256:demo-bank-token-0150', 1)
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3006, 106, 'AE', '****0129', '0129', 'sha256:demo-bank-token-0129', 1)
  into supplier_request_bank (bank_id, request_id, bank_country_code, masked_account_display, account_last4, account_hash, bank_provided_flag) values (3007, 107, 'PK', '****0161', '0161', 'sha256:demo-bank-token-0161', 1)
select 1 from dual where not exists (select 1 from supplier_request_bank where bank_id = 3001);

insert all
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4001, 101, 'TAX_CERTIFICATE', 'PENDING', 1, '{"fileName":"draft-tax.pdf","size":1200}', 1)
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4002, 102, 'TAX_CERTIFICATE', 'MISSING', 1, '{"reason":"correction requested"}', 1)
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4003, 103, 'REGISTRATION', 'VERIFIED', 1, '{"fileName":"nexa-registration.pdf","size":2400}', 0)
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4004, 104, 'REGISTRATION', 'VERIFIED', 1, '{"fileName":"noor-registration.pdf","size":2200}', 0)
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4005, 105, 'REGISTRATION', 'VERIFIED', 1, '{"fileName":"atlas-registration.pdf","size":2500}', 0)
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4006, 106, 'REGISTRATION', 'VERIFIED', 1, '{"fileName":"orion-registration.pdf","size":2600}', 0)
  into supplier_request_document (document_id, request_id, document_type, document_status, is_required, metadata_json, missing_flag) values (4007, 107, 'ACCREDITATION', 'VERIFIED', 1, '{"fileName":"summit-accreditation.pdf","size":2900}', 0)
select 1 from dual where not exists (select 1 from supplier_request_document where document_id = 4001);

insert all
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5001, 101, null, 'Draft', 'CREATE_DRAFT', 'requester_a', 'Draft created.', systimestamp - interval '7' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5002, 102, null, 'Draft', 'CREATE_DRAFT', 'requester_a', 'Draft created.', systimestamp - interval '6' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5003, 102, 'Under Review', 'Correction Requested', 'REQUEST_CORRECTION', 'reviewer_test', '{"schemaVersion":"1.0","comment":"Provide the applicable tax registration or explain the exemption.","selectedRiskFactorCodes":["MISSING_TAX"],"correctionItems":[{"fieldName":"taxRegistrationNumber","reasonCode":"MISSING_TAX","message":"Provide tax registration or exemption evidence."}]}', systimestamp - interval '2' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5004, 103, 'Submitted', 'Under Review', 'AUTO_ROUTE_TO_REVIEW', 'SYSTEM', 'All blocking checks passed.', systimestamp - interval '4' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5005, 104, 'Under Review', 'Marked Duplicate', 'MARK_DUPLICATE', 'reviewer_test', '{"schemaVersion":"1.0","comment":"Use the existing supplier.","selectedRiskFactorCodes":[],"correctionItems":[],"existingSupplierNumber":"SUP-100884"}', systimestamp - interval '8' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5006, 105, 'Under Review', 'Approved', 'APPROVE', 'reviewer_test', '{"schemaVersion":"1.0","comment":"Approved for supplier creation.","selectedRiskFactorCodes":[],"correctionItems":[]}', systimestamp - interval '2' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5007, 106, 'Submitted to Fusion', 'Created in Fusion', 'FUSION_SUCCESS', 'SYSTEM', 'Mock Fusion supplier created.', systimestamp - interval '1' day)
  into status_history (history_id, request_id, from_status, to_status, action_code, actor_user, action_comment, action_timestamp) values (5008, 107, 'Submitted to Fusion', 'Integration Failed', 'FUSION_FAILURE', 'SYSTEM', 'Temporary mock Fusion timeout.', systimestamp - interval '1' hour)
select 1 from dual where not exists (select 1 from status_history where history_id = 5001);

insert all
  into validation_result (validation_id, request_id, validation_rule_id, run_id, is_current, field_name, severity, message, is_blocking, created_at) values (6001, 102, 1, 'RUN-102-2', 1, 'supplierName', 'INFO', 'Supplier name supplied.', 0, systimestamp - interval '2' day)
  into validation_result (validation_id, request_id, validation_rule_id, run_id, is_current, field_name, severity, message, is_blocking, created_at) values (6002, 102, 3, 'RUN-102-1', 0, 'supplierTypeCode', 'ERROR', 'Earlier supplier type finding was corrected.', 1, systimestamp - interval '3' day)
  into validation_result (validation_id, request_id, validation_rule_id, run_id, is_current, field_name, severity, message, is_blocking, created_at) values (6003, 104, 8, 'RUN-104-1', 1, 'taxRegistrationNumber', 'ERROR', 'Tax registration matches SUP-100884.', 1, systimestamp - interval '10' day)
select 1 from dual where not exists (select 1 from validation_result where validation_id = 6001);

insert all
  into duplicate_match (match_id, request_id, run_id, is_current, candidate_source, candidate_supplier_ref_id, candidate_supplier_number, candidate_supplier_name, candidate_request_id, match_score, match_level, matched_fields_json, explanation, created_at) values (7001, 104, 'RUN-104-1', 1, 'EXISTING_SUPPLIER', 1001, 'SUP-100884', 'Al Noor Packaging', null, 100, 'CRITICAL', '[{"field":"taxRegistrationNumber","ruleCode":"EXACT_TAX"},{"field":"bank.accountToken","ruleCode":"EXACT_BANK_TOKEN"}]', 'Exact governed identifiers matched an existing supplier.', systimestamp - interval '10' day)
  into duplicate_match (match_id, request_id, run_id, is_current, candidate_source, candidate_supplier_ref_id, candidate_supplier_number, candidate_supplier_name, candidate_request_id, match_score, match_level, matched_fields_json, explanation, created_at) values (7002, 103, 'RUN-103-1', 1, 'EVIDENCE_ONLY', null, null, null, null, 15, 'LOW', '[{"field":"emailDomain","ruleCode":"EMAIL_DOMAIN"}]', 'Low-confidence evidence retained for Reviewer context.', systimestamp - interval '4' day)
select 1 from dual where not exists (select 1 from duplicate_match where match_id = 7001);

insert all
  into risk_assessment (risk_id, request_id, run_id, is_current, risk_score, risk_level, scoring_version, risk_reasons_json, created_at) values (8001, 103, 'RUN-103-1', 1, 15, 'LOW', '1.0', '[{"ruleCode":"VAGUE_JUSTIFICATION","weight":15,"explanation":"Reviewer should confirm business detail."}]', systimestamp - interval '4' day)
  into risk_assessment (risk_id, request_id, run_id, is_current, risk_score, risk_level, scoring_version, risk_reasons_json, created_at) values (8002, 105, 'RUN-105-1', 1, 0, 'LOW', '1.0', '[]', systimestamp - interval '7' day)
select 1 from dual where not exists (select 1 from risk_assessment where risk_id = 8001);

insert all
  into ai_summary (summary_id, request_id, prompt_version, provider_name, model_name, summary_json, source_facts_hash, created_at, created_by) values (9001, 103, 'supplier-review-v1', 'LOCAL_DETERMINISTIC_MOCK', 'facts-template-v1', '{"advisory":true,"summary":"Review the business justification and low-confidence duplicate evidence.","facts":["risk:LOW","duplicate:LOW"]}', 'sha256:demo-facts-103-v1', systimestamp - interval '4' day, 'SYSTEM')
  into ai_summary (summary_id, request_id, prompt_version, provider_name, model_name, summary_json, source_facts_hash, created_at, created_by) values (9002, 105, 'supplier-review-v1', 'LOCAL_DETERMINISTIC_MOCK', 'facts-template-v1', '{"advisory":true,"summary":"No configured risk factors were triggered.","facts":["risk:LOW"]}', 'sha256:demo-facts-105-v1', systimestamp - interval '7' day, 'SYSTEM')
select 1 from dual where not exists (select 1 from ai_summary where summary_id = 9001);

insert all
  into integration_log (log_id, request_id, integration_name, oic_instance_id, direction, status, error_category, payload_ref, response_ref, user_message, technical_message, retry_count, retry_eligible_flag, last_retry_at, last_retry_by, retry_history_json, created_at) values (10001, 106, 'SUPPLIER_CREATE', 'OIC-MOCK-106-1', 'OUTBOUND', 'SUCCESS', null, 'mock://payloads/REQ-2026-0129', 'mock://responses/REQ-2026-0129', 'Supplier created successfully.', null, 0, 0, null, null, '[]', systimestamp - interval '1' day)
  into integration_log (log_id, request_id, integration_name, oic_instance_id, direction, status, error_category, payload_ref, response_ref, user_message, technical_message, retry_count, retry_eligible_flag, last_retry_at, last_retry_by, retry_history_json, created_at) values (10002, 107, 'SUPPLIER_CREATE', 'OIC-MOCK-107-2', 'OUTBOUND', 'FAILED', 'TEMPORARY_TIMEOUT', 'mock://payloads/REQ-2026-0161', 'mock://responses/REQ-2026-0161/attempt-2', 'Supplier creation is delayed. Support can retry.', 'Deterministic mock timeout on attempt 2.', 1, 1, systimestamp - interval '1' hour, 'support_admin_test', '[{"attempt":1,"actor":"support_admin_test","timestamp":"2026-07-21T15:00:00Z","result":"FAILED","message":"Temporary timeout","oicInstanceId":"OIC-MOCK-107-2"}]', systimestamp - interval '2' day)
select 1 from dual where not exists (select 1 from integration_log where log_id = 10001);

commit;
