create table ref_business_unit (
    business_unit_id number generated by default on null as identity,
    business_unit_code varchar2(30 char),
    business_unit_name varchar2(120 char),
    fusion_mapping_code varchar2(60 char),
    active_flag number(1) default 1,
    created_at timestamp with time zone default systimestamp,
    created_by varchar2(128 char),
    updated_at timestamp with time zone,
    updated_by varchar2(128 char),
    constraint pk_ref_business_unit primary key (business_unit_id)
);

create table ref_supplier_type (
    supplier_type_id number generated by default on null as identity,
    supplier_type_code varchar2(30 char),
    supplier_type_name varchar2(120 char),
    tax_required_flag number(1) default 0,
    active_flag number(1) default 1,
    created_at timestamp with time zone default systimestamp,
    created_by varchar2(128 char),
    updated_at timestamp with time zone,
    updated_by varchar2(128 char),
    constraint pk_ref_supplier_type primary key (supplier_type_id)
);

create table ref_high_risk_country (
    country_code varchar2(2 char),
    effective_from date,
    country_name varchar2(120 char),
    risk_level varchar2(20 char),
    active_flag number(1) default 1,
    effective_to date,
    created_at timestamp with time zone default systimestamp,
    created_by varchar2(128 char),
    updated_at timestamp with time zone,
    updated_by varchar2(128 char),
    constraint pk_ref_high_risk_country primary key (country_code, effective_from)
);

create table validation_rules (
    validation_rule_id number generated by default on null as identity,
    rule_code varchar2(30 char) not null,
    rule_name varchar2(120 char) not null,
    rule_description clob not null,
    field_name varchar2(80 char),
    severity varchar2(20 char) not null,
    default_message clob not null,
    is_blocking number(1) not null,
    active_flag number(1) not null,
    created_at timestamp with time zone default systimestamp,
    created_by varchar2(128 char),
    updated_at timestamp with time zone,
    updated_by varchar2(128 char),
    constraint pk_validation_rules primary key (validation_rule_id)
);

create table ref_scoring_rule (
    rule_code varchar2(40 char),
    version varchar2(20 char),
    rule_type varchar2(20 char) not null,
    rule_name varchar2(120 char),
    weight number(7,2),
    severity varchar2(20 char),
    critical_trigger_flag number(1),
    active_flag number(1),
    created_at timestamp with time zone default systimestamp,
    created_by varchar2(128 char),
    updated_at timestamp with time zone,
    updated_by varchar2(128 char),
    constraint pk_ref_scoring_rule primary key (rule_type, rule_code, version)
);
