create table supplier_request (
    request_id number generated by default on null as identity,
    request_number varchar2(30 char) not null,
    status varchar2(30 char) not null,
    supplier_name varchar2(200 char),
    supplier_type_code varchar2(30 char),
    country_code varchar2(2 char),
    business_unit_id number,
    requester_user varchar2(128 char),
    business_justification clob,
    product_service_category varchar2(120 char),
    expected_annual_spend number(18,2),
    tax_registration_number varchar2(80 char),
    fusion_supplier_id varchar2(80 char),
    fusion_supplier_number varchar2(80 char),
    fusion_created_at timestamp with time zone,
    fusion_response_ref varchar2(500 char),
    created_at timestamp with time zone default systimestamp,
    submitted_at timestamp with time zone,
    last_updated_at timestamp with time zone default systimestamp,
    constraint pk_supplier_request primary key (request_id)
);

create table supplier_request_site (
    site_id number generated by default on null as identity,
    request_id number not null,
    site_name varchar2(120 char),
    country_code varchar2(2 char),
    address_line1 varchar2(20 char),
    address_line2 varchar2(20 char),
    city varchar2(80 char),
    region varchar2(80 char),
    postal_code varchar2(20 char),
    intended_business_unit_id number,
    is_primary number(1),
    constraint pk_supplier_request_site primary key (site_id)
);

create table supplier_request_contact (
    contact_id number generated by default on null as identity,
    request_id number not null,
    contact_name varchar2(120 char),
    contact_email varchar2(254 char),
    phone_number varchar2(40 char),
    email_domain varchar2(253 char),
    constraint pk_supplier_request_contact primary key (contact_id)
);

create table supplier_request_bank (
    bank_id number generated by default on null as identity,
    request_id number not null,
    bank_country_code varchar2(2 char),
    masked_account_display varchar2(40 char),
    account_last4 varchar2(4 char),
    account_hash varchar2(128 char),
    bank_provided_flag number(1),
    constraint pk_supplier_request_bank primary key (bank_id)
);

create table supplier_request_document (
    document_id number generated by default on null as identity,
    request_id number not null,
    document_type varchar2(60 char),
    document_status varchar2(30 char),
    is_required number(1),
    metadata_json clob,
    missing_flag number(1),
    constraint pk_supplier_request_document primary key (document_id)
);

create table status_history (
    history_id number generated by default on null as identity,
    request_id number not null,
    from_status varchar2(30 char),
    to_status varchar2(30 char),
    action_code varchar2(40 char),
    actor_user varchar2(128 char),
    action_comment clob,
    action_timestamp timestamp with time zone default systimestamp,
    constraint pk_status_history primary key (history_id)
);
