create table validation_result (
    validation_id number generated by default on null as identity,
    request_id number not null,
    validation_rule_id number not null,
    run_id varchar2(64 char),
    is_current number(1),
    field_name varchar2(80 char),
    severity varchar2(20 char),
    message clob,
    is_blocking number(1),
    created_at timestamp with time zone default systimestamp,
    constraint pk_validation_result primary key (validation_id)
);

create table duplicate_match (
    match_id number generated by default on null as identity,
    request_id number not null,
    run_id varchar2(64 char),
    is_current number(1),
    candidate_source varchar2(30 char),
    candidate_supplier_ref_id number,
    candidate_supplier_number varchar2(80 char),
    candidate_supplier_name varchar2(200 char),
    candidate_request_id number,
    match_score number(7,2),
    match_level varchar2(20 char),
    matched_fields_json clob,
    explanation clob,
    created_at timestamp with time zone default systimestamp,
    constraint pk_duplicate_match primary key (match_id)
);

create table risk_assessment (
    risk_id number generated by default on null as identity,
    request_id number not null,
    run_id varchar2(64 char),
    is_current number(1),
    risk_score number(7,2),
    risk_level varchar2(20 char),
    scoring_version varchar2(20 char),
    risk_reasons_json clob,
    created_at timestamp with time zone default systimestamp,
    constraint pk_risk_assessment primary key (risk_id)
);

create table ai_summary (
    summary_id number generated by default on null as identity,
    request_id number not null,
    prompt_version varchar2(30 char),
    provider_name varchar2(80 char),
    model_name varchar2(80 char),
    summary_json clob,
    source_facts_hash varchar2(128 char),
    created_at timestamp with time zone default systimestamp,
    created_by varchar2(128 char),
    constraint pk_ai_summary primary key (summary_id)
);
