create table existing_supplier_ref (
    supplier_ref_id number generated by default on null as identity,
    fusion_supplier_id varchar2(80 char),
    supplier_number varchar2(80 char),
    supplier_name varchar2(200 char),
    normalized_name varchar2(200 char),
    country_code varchar2(2 char),
    tax_registration_number varchar2(80 char),
    email_domain varchar2(253 char),
    phone_normalized varchar2(40 char),
    address_normalized varchar2(500 char),
    bank_account_hash varchar2(128 char),
    last_sync_at timestamp with time zone,
    constraint pk_existing_supplier_ref primary key (supplier_ref_id)
);

create table existing_supplier_site_ref (
    site_ref_id number generated by default on null as identity,
    supplier_ref_id number not null,
    fusion_site_id varchar2(80 char),
    site_name varchar2(120 char),
    country_code varchar2(2 char),
    address_normalized varchar2(500 char),
    business_unit_code varchar2(30 char),
    constraint pk_existing_supplier_site_ref primary key (site_ref_id)
);

create table integration_log (
    log_id number generated by default on null as identity,
    request_id number not null,
    integration_name varchar2(80 char),
    oic_instance_id varchar2(100 char),
    direction varchar2(20 char),
    status varchar2(30 char),
    error_category varchar2(40 char),
    payload_ref varchar2(500 char),
    response_ref varchar2(500 char),
    user_message clob,
    technical_message clob,
    retry_count number(9),
    retry_eligible_flag number(1),
    last_retry_at timestamp with time zone,
    last_retry_by varchar2(128 char),
    retry_history_json clob not null,
    created_at timestamp with time zone default systimestamp,
    constraint pk_integration_log primary key (log_id)
);
