create index ix_request_status on supplier_request (status);
create index ix_request_owner on supplier_request (requester_user, last_updated_at desc);
create index ix_request_country on supplier_request (country_code);
create index ix_request_business_unit on supplier_request (business_unit_id);
create index ix_request_supplier_type on supplier_request (supplier_type_code);
create index ix_request_submitted on supplier_request (submitted_at);
create index ix_request_fusion_number on supplier_request (fusion_supplier_number);
create index ix_site_request on supplier_request_site (request_id);
create index ix_site_country on supplier_request_site (country_code);
create index ix_site_business_unit on supplier_request_site (intended_business_unit_id);
create unique index uk_site_one_primary on supplier_request_site (case when is_primary = 1 then request_id end);
create index ix_contact_request on supplier_request_contact (request_id);
create index ix_contact_domain on supplier_request_contact (email_domain);
create index ix_bank_hash on supplier_request_bank (account_hash);
create index ix_bank_country on supplier_request_bank (bank_country_code);
create index ix_document_request_type on supplier_request_document (request_id, document_type);
create index ix_document_missing on supplier_request_document (missing_flag);
create index ix_history_request_time on status_history (request_id, action_timestamp);
create index ix_history_action on status_history (action_code);
create index ix_validation_current on validation_result (request_id, is_current, is_blocking);
create index ix_validation_rule on validation_result (validation_rule_id);
create index ix_validation_run on validation_result (run_id);
create index ix_duplicate_current on duplicate_match (request_id, is_current, match_level, match_score);
create index ix_duplicate_run on duplicate_match (run_id);
create index ix_duplicate_supplier on duplicate_match (candidate_supplier_ref_id);
create index ix_duplicate_candidate_request on duplicate_match (candidate_request_id);
create index ix_risk_current on risk_assessment (request_id, is_current);
create index ix_risk_level on risk_assessment (risk_level, created_at);
create index ix_ai_request_created on ai_summary (request_id, created_at);
create index ix_ai_facts_hash on ai_summary (source_facts_hash);
create index ix_existing_fusion_id on existing_supplier_ref (fusion_supplier_id);
create index ix_existing_name_country on existing_supplier_ref (normalized_name, country_code);
create index ix_existing_tax on existing_supplier_ref (tax_registration_number);
create index ix_existing_email_domain on existing_supplier_ref (email_domain);
create index ix_existing_phone on existing_supplier_ref (phone_normalized);
create index ix_existing_bank_hash on existing_supplier_ref (bank_account_hash);
create index ix_existing_site_supplier on existing_supplier_site_ref (supplier_ref_id);
create index ix_existing_site_fusion on existing_supplier_site_ref (fusion_site_id);
create index ix_existing_site_lookup on existing_supplier_site_ref (country_code, business_unit_code);
create index ix_integration_request on integration_log (request_id, created_at desc);
create index ix_integration_oic on integration_log (oic_instance_id);
create index ix_integration_status on integration_log (status, error_category, retry_eligible_flag);
create index ix_ref_bu_mapping on ref_business_unit (fusion_mapping_code);
create index ix_ref_bu_active on ref_business_unit (active_flag);
create index ix_ref_type_active on ref_supplier_type (active_flag);
create index ix_ref_country_active on ref_high_risk_country (active_flag, effective_to);
create index ix_validation_rule_config on validation_rules (active_flag, severity, is_blocking);
create index ix_scoring_rule_config on ref_scoring_rule (rule_type, active_flag, severity, critical_trigger_flag);
